"""Pydantic schemas package"""
from app.schemas.backup import (
    SearchRequest,
    SearchMultipleDrivesRequest,
    FileInfo,
    SearchResponse,
    BackupFileRequest,
)

from app.schemas.classification import (
    FileClassificationCreate,
    FileClassificationResponse,
    FileClassificationUpdate,
    ClassificationRuleCreate,
    ClassificationRuleResponse,
    ClassificationRuleUpdate,
    ClassificationScanCreate,
    ClassificationScanResponse,
    ClassificationScanUpdate,
    ClassificationStats,
    ClassificationReport,
    ScanRequest,
    ScanStatusResponse,
)

from app.schemas.tag import (
    FileTagCreate,
    FileTagResponse,
    FileTagUpdate,
    FileTagAssociationCreate,
    FileTagAssociationResponse,
    ApplyTagsRequest,
    ApplyTagsResponse,
    RemoveTagsRequest,
    RemoveTagsResponse,
    TagSearchRequest,
    TagSearchResponse,
    TagExportRequest,
    TagExportResponse,
    TagImportRequest,
    TagImportResponse,
    PopularTagsResponse,
)

from app.schemas.organization import (
    OrganizationActionCreate,
    OrganizationActionResponse,
    OrganizationActionUpdate,
    OrganizationTemplateCreate,
    OrganizationTemplateResponse,
    OrganizationTemplateUpdate,
    OrganizationPlanRequest,
    OrganizationPlanResponse,
    OrganizationExecuteRequest,
    OrganizationExecuteResponse,
    OrganizationPreviewRequest,
    UndoActionRequest,
    UndoActionResponse,
    RollbackPlanRequest,
    RollbackPlanResponse,
    OrganizationHistoryRequest,
    OrganizationHistoryResponse,
    OrganizationStatistics,
)

__all__ = [
    # Backup schemas
    "SearchRequest",
    "SearchMultipleDrivesRequest",
    "FileInfo",
    "SearchResponse",
    "BackupFileRequest",
    # Classification schemas
    "FileClassificationCreate",
    "FileClassificationResponse",
    "FileClassificationUpdate",
    "ClassificationRuleCreate",
    "ClassificationRuleResponse",
    "ClassificationRuleUpdate",
    "ClassificationScanCreate",
    "ClassificationScanResponse",
    "ClassificationScanUpdate",
    "ClassificationStats",
    "ClassificationReport",
    "ScanRequest",
    "ScanStatusResponse",
    # Tag schemas
    "FileTagCreate",
    "FileTagResponse",
    "FileTagUpdate",
    "FileTagAssociationCreate",
    "FileTagAssociationResponse",
    "ApplyTagsRequest",
    "ApplyTagsResponse",
    "RemoveTagsRequest",
    "RemoveTagsResponse",
    "TagSearchRequest",
    "TagSearchResponse",
    "TagExportRequest",
    "TagExportResponse",
    "TagImportRequest",
    "TagImportResponse",
    "PopularTagsResponse",
    # Organization schemas
    "OrganizationActionCreate",
    "OrganizationActionResponse",
    "OrganizationActionUpdate",
    "OrganizationTemplateCreate",
    "OrganizationTemplateResponse",
    "OrganizationTemplateUpdate",
    "OrganizationPlanRequest",
    "OrganizationPlanResponse",
    "OrganizationExecuteRequest",
    "OrganizationExecuteResponse",
    "OrganizationPreviewRequest",
    "UndoActionRequest",
    "UndoActionResponse",
    "RollbackPlanRequest",
    "RollbackPlanResponse",
    "OrganizationHistoryRequest",
    "OrganizationHistoryResponse",
    "OrganizationStatistics",
]
